import {parseCalendar,planEvent} from './calendar-import.js';
const failure=(status,message)=>Object.assign(Error(message),{status});
export function calendarFeedURL(raw){let u;try{u=new URL(String(raw||'').trim().replace(/^webcal:/i,'https:'));}catch{throw failure(400,'Paste a valid published calendar link.');}if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||u.hash)throw failure(400,'Use a read-only HTTPS or webcal calendar link.');let provider='';if(/^p\d+-caldav\.icloud\.com$/.test(u.hostname)&&u.pathname.startsWith('/published/'))provider='Apple / iCloud';else if(u.hostname==='calendar.google.com'&&u.pathname.startsWith('/calendar/ical/')&&u.pathname.endsWith('.ics'))provider='Google Calendar';else if(['outlook.live.com','outlook.office365.com','outlook.office.com'].includes(u.hostname)&&u.pathname.startsWith('/owa/calendar/')&&u.pathname.endsWith('.ics'))provider='Outlook';if(!provider)throw failure(400,'Use a published Apple/iCloud, Google or Outlook calendar feed. Other calendars can be imported as .ics files.');return {url:u.href,provider};}
export async function readCalendarFeed(raw,fetcher=fetch,now=new Date()){const source=calendarFeedURL(raw);let response;try{response=await fetcher(source.url,{redirect:'error',signal:AbortSignal.timeout(12000),headers:{Accept:'text/calendar'}});}catch{throw failure(502,'The calendar could not be reached. Check the published link and try again.');}if(!response.ok)throw failure(502,'The calendar provider did not return a readable feed. Check its sharing settings.');if(Number(response.headers.get('content-length'))>2000000)throw failure(413,'This calendar is too large. Use a separate calendar for outfits and occasions.');let size=0,parts=[];for await(const chunk of response.body){size+=chunk.length;if(size>2000000)throw failure(413,'This calendar is too large. Use a smaller occasions calendar.');parts.push(Buffer.from(chunk));}const from=new Date(now.getTime()+7200000).toISOString().slice(0,10),end=new Date(from+'T12:00:00Z');end.setUTCFullYear(end.getUTCFullYear()+1);let parsed;try{parsed=parseCalendar(Buffer.concat(parts).toString('utf8'),from,end.toISOString().slice(0,10));}catch{throw failure(400,'This link did not contain a supported calendar file.');}return {...source,...parsed,from};}
export function applyCalendarFeed(user,result,uuid){const previous=user.calendarFeed||{},state=user.state,old=previous.groups||{},groups={};for(const e of result.events){(groups[e.date]??=[]).push(e.name);}for(const d of Object.keys(groups))groups[d]=[...new Set(groups[d])].join(' · ').slice(0,160);const applied={...(previous.applied||{})},manual={...(previous.manual||{})},autoPlans={...(previous.autoPlans||{})};let prepared=0,changed=0;state.events??={};
 for(const date of new Set([...Object.keys(old),...Object.keys(groups)])){if(date<result.from||old[date]===groups[date])continue;if(!groups[date]&&result.warnings.length)continue;changed++;if(state.events[date]===applied[date]){if(manual[date])state.events[date]=manual[date];else delete state.events[date];}else if(!old[date])manual[date]=state.events[date]||'';else manual[date]=state.events[date]||'';
  if(autoPlans[date]&&state.plans[date]===autoPlans[date])delete state.plans[date];delete autoPlans[date];
  if(groups[date]){const label=[state.events[date],groups[date]].filter(Boolean).join(' · ').slice(0,160),before=state.plans[date];planEvent(state,date,label,'',uuid);applied[date]=state.events[date];if(!before&&state.plans[date]){autoPlans[date]=state.plans[date];prepared++;}}else{delete applied[date];delete manual[date];}
 }
 user.calendarFeed={url:result.url,provider:result.provider,lastSync:Date.now(),groups,applied,manual,autoPlans,warnings:result.warnings};return {prepared,changed};}
export const calendarStatus=user=>({connected:!!user.calendarFeed?.url,provider:user.calendarFeed?.provider||'',lastSync:user.calendarFeed?.lastSync||0,warnings:user.calendarFeed?.warnings||[]});
