import {quickLooks} from './local-stylist.js';
import {validDate} from './calendar-ui.js';
const unescapeText=s=>String(s||'').replace(/\\([nN,;\\])/g,(_,c)=>/[nN]/.test(c)?' ':c).trim().slice(0,160);
function eventDate(raw){const m=String(raw).match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?(Z)?)?$/);if(!m)return '';let date=m[1]+'-'+m[2]+'-'+m[3];if(!validDate(date))return '';if(m[7]){const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+(m[6]||0))+7200000);date=d.toISOString().slice(0,10);}return date;}
export function parseCalendar(text,from,to){if(typeof text!=='string'||text.length>2000000||!text.includes('BEGIN:VCALENDAR'))throw Error('Choose a calendar export in .ics format, smaller than 2 MB.');const rows=text.replace(/\r?\n[ \t]/g,'').split(/\r?\n/),records=[];let event=null,depth=0;for(const row of rows){if(row==='BEGIN:VEVENT'){event={};depth=0;continue;}if(row==='END:VEVENT'){if(event)records.push(event);event=null;continue;}if(!event)continue;if(row.startsWith('BEGIN:')){depth++;continue;}if(row.startsWith('END:')){depth--;continue;}if(depth)continue;const i=row.indexOf(':');if(i<0)continue;const key=row.slice(0,i).split(';')[0].toUpperCase();(event[key]??=[]).push(row.slice(i+1));if(records.length>2000)throw Error('Export a smaller calendar with fewer than 2,000 events.');}
 const warnings=new Set(),output=new Map(),overrides=new Set(records.filter(e=>e['RECURRENCE-ID']).map(e=>(e.UID?.[0]||'')+'|'+eventDate(e['RECURRENCE-ID'][0])));
 for(const e of records){if(e.STATUS?.[0]==='CANCELLED')continue;const start=eventDate(e.DTSTART?.[0]),name=unescapeText(e.SUMMARY?.[0]);if(!start||!name)continue;const uid=e.UID?.[0]||name+'|'+start,excluded=new Set((e.EXDATE||[]).flatMap(v=>v.split(',')).map(eventDate));const dates=[start];const rule=Object.fromEntries((e.RRULE?.[0]||'').split(';').filter(Boolean).map(v=>v.split('=')));
 if(rule.FREQ){const allowed=['FREQ','INTERVAL','COUNT','UNTIL','BYMONTH','BYMONTHDAY'];if(rule.FREQ==='YEARLY'&&Object.keys(rule).every(k=>allowed.includes(k))&&!String(rule.BYMONTH||'').includes(',')&&!String(rule.BYMONTHDAY||'').includes(',')){const interval=Math.max(1,Number(rule.INTERVAL)||1),month=Number(rule.BYMONTH)||Number(start.slice(5,7)),day=Number(rule.BYMONTHDAY)||Number(start.slice(8)),first=Number(start.slice(0,4)),last=Number(to.slice(0,4)),count=Number(rule.COUNT)||Infinity,until=eventDate(rule.UNTIL)||to;for(let y=first+interval;y<=last;y+=interval){if((y-first)/interval>=count)break;const d=y+'-'+String(month).padStart(2,'0')+'-'+String(day).padStart(2,'0');if(validDate(d)&&d<=until)dates.push(d);}}else warnings.add('Some repeating events use a recurrence pattern this importer cannot expand yet. Only their listed dates are included.');}
 for(const value of e.RDATE||[])dates.push(...value.split(',').map(eventDate));
 for(const date of new Set(dates)){if(!date||date<from||date>to||excluded.has(date)||(!e['RECURRENCE-ID']&&overrides.has(uid+'|'+date)))continue;const key=uid.slice(0,210)+'|'+date;output.set(key,{key,date,name,occasion:eventOccasion(name)});}
 }
 return {events:[...output.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(0,100),warnings:[...warnings,...(output.size>100?['Only the first 100 events are shown.']:[])]};}
export function eventOccasion(name){return /wedding|troue/i.test(name)?'Wedding guest':/birthday|verjaar|dinner|party|celebrat/i.test(name)?'Dinner':/work|meeting|office|interview/i.test(name)?'Work':/travel|flight|holiday/i.test(name)?'Travel':'Everyday';}
export function planEvent(state,date,name,occasion,uuid){state.events??={};state.events[date]=name;if(state.plans[date])return 'Your existing planned outfit was kept.';try{const look=quickLooks(state,{occasion:occasion||eventOccasion(name),weather:'Mild',ownedOnly:true})[0];const protectedIds=new Set(Object.values(state.plans));if(protectedIds.size>=80)return 'Event saved. Your outfit collection is full; remove an old plan before generating another.';const id=uuid();state.outfits.unshift({...look,id,batch:id,name:name+' · '+look.name,occasion:occasion||eventOccasion(name),gender:state.profile.gender,created:Date.now(),saved:true,image:'',renderStatus:'pending',reason:look.reason+' Prepared for '+name+'. Check the weather nearer the date.'});state.plans[date]=id;protectedIds.add(id);state.outfits=[...state.outfits.filter(o=>protectedIds.has(o.id)),...state.outfits.filter(o=>!protectedIds.has(o.id))].slice(0,80);return 'An outfit is ready for '+date+'.';}catch(e){return 'Event saved. Add available wardrobe pieces to prepare its outfit. '+e.message;}}
