
export const garmentBackdrop='#f2ede5';
let worker,serial=0;const jobs=new Map();
function getWorker(){if(worker)return worker;worker=new Worker(new URL('./garment-worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{const job=jobs.get(data.id);if(!job)return;if(data.progress){job.progress(data.progress);return;}jobs.delete(data.id);clearTimeout(job.timer);data.error?job.reject(Error(data.error)):job.resolve(data);};worker.onerror=()=>{for(const job of jobs.values()){clearTimeout(job.timer);job.reject(Error('Automatic cleanup is unavailable on this device.'));}jobs.clear();worker?.terminate();worker=null;};return worker;}
export function subjectBounds({width:w,height:h,data:d}){let left=w,top=h,right=-1,bottom=-1,count=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>48){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);count++;}if(count<w*h*.005||count>w*h*.985)throw Error('The clothing edges need a touch-up.');return {x:left,y:top,width:right-left+1,height:bottom-top+1};}
export function enhancePixels(frame){const {width:w,height:h,data:d}=frame,copy=d.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=(y*w+x)*4;if(copy[p+3]<240)continue;const neighbours=[p-4,p+4,p-w*4,p+w*4];if(neighbours.some(q=>copy[q+3]<240))continue;const lum=q=>.2126*copy[q]+.7152*copy[q+1]+.0722*copy[q+2],current=lum(p),average=neighbours.reduce((v,q)=>v+lum(q),0)/4,detail=Math.max(-5,Math.min(5,(current-average)*.2));for(let c=0;c<3;c++)d[p+c]=Math.max(0,Math.min(255,copy[p+c]+detail));}return frame;}
async function decode(src){const image=new Image();image.src=src;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);return canvas;}
export async function neutralGarment(cutout){const source=await decode(cutout),ctx=source.getContext('2d',{willReadFrequently:true}),frame=ctx.getImageData(0,0,source.width,source.height),bounds=subjectBounds(frame);enhancePixels(frame);ctx.putImageData(frame,0,0);const canvas=document.createElement('canvas');canvas.width=canvas.height=900;const out=canvas.getContext('2d');out.fillStyle=garmentBackdrop;out.fillRect(0,0,900,900);out.imageSmoothingEnabled=true;out.imageSmoothingQuality='high';const scale=Math.min(720/bounds.width,720/bounds.height),w=bounds.width*scale,h=bounds.height*scale;out.drawImage(source,bounds.x,bounds.y,bounds.width,bounds.height,(900-w)/2,(900-h)/2,w,h);return canvas.toDataURL('image/jpeg',.92);}
export async function prepareGarmentPhoto(original,progress=()=>{}){
 progress('Removing the background automatically…');const canvas=await decode(original),ctx=canvas.getContext('2d',{willReadFrequently:true}),frame=ctx.getImageData(0,0,canvas.width,canvas.height);
 let cutout;
 // Already transparent photographs need no model download or inference.
 if(frame.data.some((v,i)=>i%4===3&&v<10))cutout=original;
 else try{const id=++serial,result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{jobs.delete(id);reject(Error('Cleanup took too long.'));if(!jobs.size){worker?.terminate();worker=null;}},150000);jobs.set(id,{resolve,reject,timer,progress});try{getWorker().postMessage({id,width:frame.width,height:frame.height,rgba:frame.data.buffer},[frame.data.buffer]);}catch(e){jobs.delete(id);clearTimeout(timer);reject(e);}});ctx.putImageData(new ImageData(new Uint8ClampedArray(result.rgba),result.width,result.height),0,0);cutout=canvas.toDataURL('image/png');subjectBounds(ctx.getImageData(0,0,canvas.width,canvas.height));}
 catch(error){console.warn('Background model unavailable: '+error.message);throw Error('Background cleanup did not finish. Retry or use Touch up background.');}
 progress('Enhancing and centring your piece…');return {image:await neutralGarment(cutout),cutout,original,photoTreatment:'catalogue-v1'};
}
