const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createNotifications({api,modal,getUser,toast,navigate,openPost}){let items=[],canAnnounce=false,epoch=0;const badge=()=>{const el=document.querySelector('#notification-count');if(el){const n=items.filter(i=>!i.read).length;el.textContent=n>99?'99+':n;el.hidden=!n;}};
 async function load(){if(!getUser()){items=[];badge();return;}const token=epoch,owner=getUser().id;const d=await api('notifications');if(epoch!==token||getUser()?.id!==owner)return;items=d.items;canAnnounce=d.canAnnounce;badge();}
 function show(){modal('Notifications',`<div class="notification-legend"><span class="notice-owner">From Closet</span><span class="notice-friend">Friends’ outfits</span><span class="notice-request">Friend requests</span></div><div class="actions"><button class="btn quiet" data-notice="read-all">Mark all as read</button>${canAnnounce?'<button class="btn" data-notice="compose">Write an announcement</button>':''}</div><div class="notification-list">${items.map(n=>`<button class="notification-card notice-${n.kind==='announcement'?'owner':n.kind}" data-notice="open" data-id="${esc(n.id)}"><span class="notification-kind">${n.kind==='announcement'?'FROM CLOSET':n.kind==='friend'?'FRIEND’S OUTFIT':'FRIEND REQUEST'}${n.read?'':' · NEW'}</span><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p>${n.created?`<small>${new Date(n.created).toLocaleDateString('en-ZA')}</small>`:''}</button>`).join('')||'<div class="empty"><h3>You’re all caught up.</h3><p>Updates from Closet and your friends will appear here.</p></div>'}</div>`);}
 async function open(){if(!getUser()){modal('Notifications','<p class="sub">Sign in to see updates from Closet and your friends.</p>');return;}try{await load();show();}catch(e){toast(e.message);}}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-notice]');if(!b)return;try{if(b.dataset.notice==='read-all'){await api('notifications/read',{all:true});await load();show();}else if(b.dataset.notice==='compose'){modal('Message from Closet',`<form id="announcement-form"><p class="sub">This announcement will be visible to every account on this installation.</p><label class="field">Title<input name="title" required maxlength="100"></label><label class="field">Message<textarea name="body" required maxlength="1500"></textarea></label><button class="btn primary">Publish announcement</button></form>`);}else{const n=items.find(n=>n.id===b.dataset.id);if(!n)return;await api('notifications/read',{id:n.id});n.read=true;badge();if(n.kind==='friend'){await openPost(n.postId);}else if(n.kind==='request'){document.querySelector('#modal').close();navigate('friends');}else modal(esc(n.title),`<span class="tag">FROM CLOSET</span><p class="announcement-text">${esc(n.body)}</p>`);}}catch(e){toast(e.message);}});
 document.addEventListener('submit',async e=>{if(e.target.id!=='announcement-form')return;e.preventDefault();const form=e.target,b=form.querySelector('button');b.disabled=true;try{await api('notifications/announce',Object.fromEntries(new FormData(form)));await load();show();toast('Announcement published.');}catch(e){toast(e.message);b.disabled=false;}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)load().catch(()=>{});});const timer=setInterval(()=>{if(!document.hidden)load().catch(()=>{});},60000);
 return {open,load,badge,clear(){epoch++;items=[];canAnnounce=false;badge();}};
}
