const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createNotifications({api,modal,getUser,toast,navigate,openPost}){let items=[],canAnnounce=false,epoch=0,filter='all';const badge=()=>{const el=document.querySelector('#notification-count');if(el){const n=items.filter(i=>!i.read).length;el.textContent=n>99?'99+':n;el.hidden=!n;}};
 async function load(){if(!getUser()){items=[];badge();return;}const token=epoch,owner=getUser().id;const d=await api('notifications');if(epoch!==token||getUser()?.id!==owner)return;items=d.items;canAnnounce=d.canAnnounce;badge();}
 function show(){modal('Notifications',`<div class="notification-toolbar"><div class="notification-filters" aria-label="Notification filters">${[['all','All'],['unread','Unread'],['announcement','MOOI'],['friends','Friends']].map(([key,label])=>`<button type="button" class="chip ${filter===key?'active':''}" data-notice="filter" data-id="${key}" aria-pressed="${filter===key}">${label}</button>`).join('')}</div><details class="notification-menu"><summary aria-label="Notification actions">Manage</summary><div><button class="btn quiet" data-notice="read-all">Mark all read</button><button class="btn quiet" data-notice="clear-all">Clear all</button><button class="btn quiet" data-notice="restore">Restore cleared</button>${canAnnounce?'<button class="btn quiet" data-notice="compose">New announcement</button>':''}</div></details></div><div class="notification-list">${items.filter(n=>filter==='all'||filter==='unread'&&!n.read||filter==='announcement'&&n.kind==='announcement'||filter==='friends'&&n.kind!=='announcement').map(n=>`<div class="notification-entry ${n.read?'is-read':'is-unread'}"><button class="notification-card notice-${n.kind==='announcement'?'owner':n.kind}" data-notice="open" data-id="${esc(n.id)}"><span class="notification-kind">${n.kind==='announcement'?'FROM MOOI':n.kind==='friend'?'FRIEND’S OUTFIT':'FRIEND REQUEST'}${n.read?'':' · NEW'}</span><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p>${n.created>1?`<small>${new Date(n.created).toLocaleDateString('en-ZA')}</small>`:''}</button><button class="btn quiet notice-clear" data-notice="clear" data-id="${esc(n.id)}" aria-label="Clear ${esc(n.title)}">Clear</button></div>`).join('')||'<div class="empty"><h3>You’re all caught up.</h3><p>No notifications here.</p></div>'}</div>`);}
 async function open(){if(!getUser()){modal('Notifications','<p class="sub">Sign in to see updates from MOOI and your friends.</p>');return;}try{await load();show();}catch(e){toast(e.message);}}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-notice]');if(!b)return;try{if(b.dataset.notice==='filter'){filter=b.dataset.id;show();return;}if(b.dataset.notice==='back'){show();return;}b.disabled=true;if(['clear','clear-all','restore'].includes(b.dataset.notice)){await api(b.dataset.notice==='restore'?'notifications/restore':'notifications/clear',{id:b.dataset.id,all:b.dataset.notice==='clear-all'});await load();show();}else if(b.dataset.notice==='read-all'){await api('notifications/read',{all:true});await load();show();}else if(b.dataset.notice==='compose'){modal('Message from MOOI',`<button type="button" class="btn quiet flow-back" data-notice="back">Back</button><form id="announcement-form"><p class="sub">Visible to everyone on MOOI.</p><label class="field">Title<input name="title" required maxlength="100"></label><label class="field">Message<textarea name="body" required maxlength="1500"></textarea></label><button class="btn primary">Publish announcement</button></form>`);}else{const n=items.find(n=>n.id===b.dataset.id);if(!n)return;await api('notifications/read',{id:n.id});n.read=true;badge();if(n.kind==='friend'){await openPost(n.postId);}else if(n.kind==='request'){document.querySelector('#modal').close();navigate('friends');}else modal(esc(n.title),`<button type="button" class="btn quiet flow-back" data-notice="back">Back to notifications</button><span class="tag">FROM MOOI</span><p class="announcement-text">${esc(n.body)}</p>`);}}catch(e){toast(e.message);}finally{if(b.isConnected)b.disabled=false;}});
 document.addEventListener('submit',async e=>{if(e.target.id!=='announcement-form')return;e.preventDefault();const form=e.target,b=form.querySelector('button');b.disabled=true;try{await api('notifications/announce',Object.fromEntries(new FormData(form)));await load();show();toast('Announcement published.');}catch(e){toast(e.message);b.disabled=false;}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)load().catch(()=>{});});const timer=setInterval(()=>{if(!document.hidden)load().catch(()=>{});},60000);
 return {open,load,badge,clear(){epoch++;filter='all';items=[];canAnnounce=false;badge();}};
}
