const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const choices={
 bodyShape:['Straight / rectangular','Hourglass','Pear / triangle','Apple / rounded','Inverted triangle','Not sure','Prefer not to say'],
 bodyNotes:['More room at the shoulders','More room at the bust','More room at the waist','More room at the hips','Petite lengths','Tall lengths'],
 lifestyle:['Office','Working from home','Campus / studying','On my feet at work','Parenting','Active / outdoors','Social outings'],
 styles:['Minimal','Classic','Casual','Streetwear','Romantic','Bohemian','Sporty','Bold / statement','Elegant'],
 favouriteColours:['Neutrals','Black & white','Earth tones','Pastels','Bright colours','Jewel tones','Denim blues'],
 avoid:['Heels','Tight fits','Short hemlines','Low necklines','Sleeveless pieces','Bold prints','Itchy fabrics','Nothing in particular'],
 comfort:['Relaxed fits','Stretch fabrics','Flat shoes','Breathable fabrics','Soft textures','Light layers','Covered silhouettes'],
 goals:['Everyday outfits','Work looks','Occasion dressing','Trying new colours','Rewearing my clothes','Packing for trips','Finding my style','Shopping thoughtfully']
};
export function splitChoices(value,options){const parts=String(value||'').split(',').map(s=>s.trim()).filter(Boolean);return {selected:options.filter(o=>parts.some(p=>p.toLowerCase()===o.toLowerCase())),custom:parts.filter(p=>!options.some(o=>o.toLowerCase()===p.toLowerCase())).join(', ')};}
const input=(title,key,value,placeholder='')=>{const options=choices[key],saved=splitChoices(value,options);return `<fieldset class="field choice-question" data-choice-group="${key}"><legend>${title}</legend><p class="choice-hint">${key==='bodyShape'?'Choose one, or skip this question.':'Choose all that feel like you.'}</p><input type="hidden" name="${key}" value="${esc(value)}"><div class="style-choices">${options.map((option,index)=>`<label class="style-choice"><input type="${key==='bodyShape'?'radio':'checkbox'}" ${key==='bodyShape'?'name="silhouetteChoice"':''} data-choice value="${esc(option)}" ${saved.selected.includes(option)?'checked':''}><span>${esc(option)}</span></label>`).join('')}</div><details class="choice-custom" ${saved.custom?'open':''}><summary>Something else? Add your own</summary><label>Your own answer<input data-choice-custom type="text" value="${esc(saved.custom)}" placeholder="${esc(placeholder)}" maxlength="300"></label></details></fieldset>`;};
export function refreshChoices(form){form.querySelectorAll('[data-choice-group]').forEach(group=>{const value=form.elements[group.dataset.choiceGroup].value,options=[...group.querySelectorAll('[data-choice]')],saved=splitChoices(value,options.map(i=>i.value));options.forEach(i=>i.checked=saved.selected.includes(i.value));group.querySelector('[data-choice-custom]').value=saved.custom;group.querySelector('details').open=!!saved.custom;});}
export function initChoices(form){form.addEventListener('input',e=>{const group=e.target.closest('[data-choice-group]');if(!group||!e.target.matches('[data-choice],[data-choice-custom]'))return;const selected=[...group.querySelectorAll('[data-choice]:checked')].map(i=>i.value),custom=group.querySelector('[data-choice-custom]').value.trim();form.elements[group.dataset.choiceGroup].value=[...selected,custom].filter(Boolean).join(', ');});}
export function personalForm(p={},profile={}){return `<form id="personal-form"><p class="sub">A few details help MOOI style for your real life. Every question and the photo are optional.</p><fieldset class="personal-section"><legend>01 / Your silhouette</legend><div class="personal-photo"><div id="personal-preview">${p.photo?`<img class="preview" src="${p.photo}" alt="Your personal styling reference">`:'<p class="sub">A clear, fully clothed, full-length photo works best.</p>'}</div><label class="upload">Upload a photo of yourself<input id="personal-photo" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="btn quiet" data-action="remove-personal-photo">Remove photo</button></div><p class="sub">Your photo is saved with your local account. It is sent to OpenAI only when you choose analysis or enable it for outfit images. You can remove it here. Existing generated images and exported backups keep their own copies.</p><label class="checkrow"><input type="checkbox" id="analysis-consent">Send this photo to OpenAI to suggest my silhouette and fit notes</label><button type="button" class="btn" data-action="analyse-personal">Suggest from my photo</button><p id="personal-status" class="sub" role="status"></p>${input('Body shape / silhouette (optional)','bodyShape',p.bodyShape,'Describe yourself, or review an AI suggestion')}${input('Fit notes','bodyNotes',p.bodyNotes,'e.g. more room at the shoulders')}<p class="sub">A photo cannot establish exact measurements. Suggestions are approximate; keep only what feels right to you.</p><label class="checkrow"><input type="checkbox" name="usePhoto" ${p.usePhoto?'checked':''}>Use my photo as a reference for future AI outfit images</label></fieldset><fieldset class="personal-section"><legend>02 / Your everyday style</legend>${input('What does a typical week look like?','lifestyle',p.lifestyle,'Office, working from home, campus, weekends out…')}${input('Which styles feel most like you?','styles',(profile.styles||[]).join(', '),'Minimal, classic, streetwear, romantic…')}${input('Which colours do you love?','favouriteColours',p.favouriteColours,'Neutrals, bright colours, all black…')}${input('What do you avoid wearing?','avoid',p.avoid,'Heels, tight waistbands, certain fabrics…')}${input('What makes an outfit comfortable for you?','comfort',p.comfort,'Loose layers, flat shoes, breathable fabrics…')}${input('What would you like help with?','goals',p.goals,'Work outfits, trying colour, rewearing my clothes…')}</fieldset><div class="actions"><button class="btn primary" id="personal-save">Save my style</button><button type="button" class="btn quiet" data-action="close">Not now</button></div></form>`;}
