import {cleanPlainBackground,eraseRegion} from './photo-tools.js';

// All editing happens locally. Apply is the only operation that changes the draft.
export async function openPhotoEditor(host,original,current,onApply){
 const image=new Image();image.src=original;await image.decode();
 host.innerHTML=`<section class="cutout-editor"><p class="eyebrow">BACKGROUND STUDIO</p><p class="sub" role="status">Tap the background to remove it. Use the brush for small details.</p><div class="actions"><button type="button" class="btn" data-cutout="auto">Auto clean</button><button type="button" class="btn primary" data-cutout="wand" aria-pressed="true">Tap background</button><button type="button" class="btn" data-cutout="erase" aria-pressed="false">Erase brush</button><button type="button" class="btn" data-cutout="restore" aria-pressed="false">Restore brush</button><button type="button" class="btn" data-cutout="undo">Undo</button></div><div class="row"><label>Brush size<input type="range" min="2" max="100" value="28" data-cutout-size></label><label>Colour tolerance<input type="range" min="5" max="100" value="35" data-cutout-tolerance></label></div><div class="cutout-board"><canvas aria-label="Clothing background editor: tap background or drag to erase and restore"></canvas></div><div class="actions"><button type="button" class="btn primary" data-cutout="apply">Use this cutout</button><button type="button" class="btn" data-cutout="cancel">Cancel</button></div></section>`;
 const canvas=host.querySelector('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});canvas.width=image.width;canvas.height=image.height;ctx.drawImage(image,0,0);const source=ctx.getImageData(0,0,canvas.width,canvas.height);
 if(current&&current!==original){const edited=new Image();edited.src=current;await edited.decode();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(edited,0,0,canvas.width,canvas.height);}
 const status=host.querySelector('[role="status"]'),history=[];let mode='wand',drawing=false,last=null;
 const remember=()=>{history.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(history.length>8)history.shift();};
 const point=e=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width-1,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height-1,(e.clientY-r.top)*canvas.height/r.height))};};
 const brush=p=>{const size=Number(host.querySelector('[data-cutout-size]').value)*canvas.width/canvas.getBoundingClientRect().width;ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,size/2,0,Math.PI*2);ctx.globalCompositeOperation='destination-out';ctx.fill();ctx.restore();};
 const paint=p=>{if(mode!=='restore')return brush(p);const size=Number(host.querySelector('[data-cutout-size]').value)*canvas.width/canvas.getBoundingClientRect().width;ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,size/2,0,Math.PI*2);ctx.clip();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);ctx.restore();};
 canvas.addEventListener('pointerdown',e=>{e.preventDefault();remember();const p=point(e);if(mode==='wand'){const frame=ctx.getImageData(0,0,canvas.width,canvas.height);eraseRegion(frame,Math.floor(p.x),Math.floor(p.y),Number(host.querySelector('[data-cutout-tolerance]').value));ctx.putImageData(frame,0,0);status.textContent='Background removed. Review the edges, then use this cutout.';}else{drawing=true;last=p;canvas.setPointerCapture(e.pointerId);paint(p);}});
 canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e),steps=Math.ceil(Math.hypot(p.x-last.x,p.y-last.y)/2);for(let n=1;n<=steps;n++)paint({x:last.x+(p.x-last.x)*n/steps,y:last.y+(p.y-last.y)*n/steps});last=p;});
 for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{drawing=false;last=null;});
 host.onclick=async e=>{const action=e.target.closest('[data-cutout]')?.dataset.cutout;if(!action)return;try{if(['wand','erase','restore'].includes(action)){mode=action;host.querySelectorAll('[aria-pressed]').forEach(b=>{const selected=b.dataset.cutout===mode;b.setAttribute('aria-pressed',String(selected));b.classList.toggle('primary',selected);});}else if(action==='undo'){const frame=history.pop();if(frame)ctx.putImageData(frame,0,0);}else if(action==='cancel'){host.innerHTML='';}else if(action==='apply'){const data=canvas.toDataURL('image/png');if(data.length>=4000000)throw Error('The cutout is too large. Remove more background or use a smaller photo.');onApply(data);host.innerHTML='';}else if(action==='auto'){await auto();}}catch(err){status.textContent=err.message;}};
 async function auto(){try{const cleaned=new Image();cleaned.src=await cleanPlainBackground(original);await cleaned.decode();remember();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(cleaned,0,0);status.textContent='Auto clean ready. Touch up edges or restore any missing fabric, then use this cutout.';}catch{status.textContent='This background needs a touch-up. Tap its areas to remove them, or use the erase brush.';}}
 await auto();
}
