import {request} from 'node:http';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createApp} from '../server.js';
async function fixture(options={}){const dir=mkdtempSync(path.join(tmpdir(),'mooi-pilot-')),server=createApp({...options,dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';return {async call(route,body,method='POST',extra={}){const r=await new Promise((resolve,reject)=>{const req=request(base+route,{method:body===undefined?'GET':method,headers:{'Content-Type':'application/json',cookie,...(options.publicOrigin?{Host:new URL(options.publicOrigin).host,Origin:options.publicOrigin}:{}),...extra}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(new Response(Buffer.concat(chunks),{status:res.statusCode,headers:Object.fromEntries(Object.entries(res.headers).map(([k,v])=>[k,Array.isArray(v)?v.join(', '):v]))})));});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body));});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text(),cookie:set};},async close(){await new Promise(r=>server.close(r));assert.ok(dir.startsWith(path.join(tmpdir(),'mooi-pilot-')));rmSync(dir,{recursive:true,force:true});}};}
const signup={email:'owner@example.com',password:'long-test-password',name:'Tester',gender:'Female'};
test('hosted pilot requires invitation, uses secure sessions and rotates recovery codes',async()=>{const f=await fixture({apiKey:'',publicOrigin:'https://mooi.example',pilotCode:'private-pilot-code'});try{
 assert.equal((await f.call('/api/auth/register',signup)).status,403);
 const account=await f.call('/api/auth/register',{...signup,pilotCode:'private-pilot-code'});assert.equal(account.status,200,account.data.error);assert.match(account.cookie,/Secure/);assert.equal(account.data.recoveryCode.length,48);
 assert.equal((await f.call('/api/state',undefined,'GET',{Origin:'https://other.example'})).status,403);
 const reset=await f.call('/api/auth/recover',{email:signup.email,recoveryCode:account.data.recoveryCode,password:'another-long-password'});assert.equal(reset.status,200);assert.notEqual(reset.data.recoveryCode,account.data.recoveryCode);
 assert.equal((await f.call('/api/auth/recover',{email:signup.email,recoveryCode:account.data.recoveryCode,password:'third-long-password'})).status,401);
 assert.equal((await f.call('/api/auth/login',signup)).status,401);
 assert.equal((await f.call('/api/auth/login',{...signup,password:'another-long-password'})).status,200);
 assert.equal((await f.call('/manifest.webmanifest')).status,200);assert.equal((await f.call('/sw.js')).status,200);assert.equal((await f.call('/.env')).status,404);
 }finally{await f.close();}});
test('stylist passes feedback and live weather, enforces owned-only and locked pieces',async()=>{let payload,invalid=false;const f=await fixture({apiKey:'test',weatherFetch:async url=>url.includes('geocoding')?Response.json({results:[{name:'Johannesburg',country_code:'ZA',latitude:1,longitude:1}]}):Response.json({current:{temperature_2m:20,apparent_temperature:19,weather_code:3},daily:{precipitation_probability_max:[5]}}),fetch:async(url,opts)=>{const body=JSON.parse(opts.body);payload=JSON.parse(body.input[0].content[0].text);return Response.json({output_text:JSON.stringify({outfits:[['a','b'],['a','c'],['a','b','c']].map((ids,i)=>({name:'Look '+i,ids,suggestions:invalid?[{name:'Invented addition',category:'top',retailer:'Bash'}]:[],reason:'Use your own pieces.'}))})});}});try{
 let r=await f.call('/api/auth/register',signup);const state=r.data.state;state.items=['a','b','c'].map(id=>({id,name:id,cat:'top',colour:'White'}));state.stylistFeedback=[{reason:'Prefer flat shoes',note:'For walking',created:Date.now()}];await f.call('/api/state',{state,revision:r.data.revision},'PUT');
 r=await f.call('/api/generate-outfits',{ownedOnly:true,lockedIds:['a'],weather:'Automatic',city:'Johannesburg'});assert.equal(r.status,200);assert.ok(r.data.outfits.every(o=>!o.suggestions.length&&o.ids.includes('a')));assert.equal(payload.feedback[0].reason,'Prefer flat shoes');assert.match(payload.weather,/20°C/);
 invalid=true;assert.equal((await f.call('/api/generate-outfits',{ownedOnly:true,lockedIds:['a']})).status,502);assert.equal((await f.call('/api/state')).data.state.outfits.length,3);
 assert.equal((await f.call('/api/generate-outfits',{lockedIds:['missing']})).status,400);
 }finally{await f.close();}});
test('curated catalogue restricts imports to owner and validates retailer domains',async()=>{const f=await fixture({apiKey:'',ownerEmail:signup.email});try{await f.call('/api/auth/register',signup);const p={name:'Test product fixture',category:'top',retailer:'Bash',url:'https://bash.com/example-test-product',price:100,sizes:['M'],checkedAt:'2026-01-01'};assert.equal((await f.call('/api/products',{products:[p]},'PUT')).status,200);assert.equal((await f.call('/api/products?category=top')).data.products[0].price,100);assert.equal((await f.call('/api/products',{products:[{...p,url:'https://bash.com.evil.example/product'}]},'PUT')).status,400);await f.call('/api/auth/register',{...signup,email:'other@example.com'});assert.equal((await f.call('/api/products',{products:[]},'PUT')).status,403);}finally{await f.close();}});
