export const categories={top:'Tops',bottom:'Bottoms',outer:'Layers',shoe:'Shoes',dress:'Dresses',bag:'Bags',jewellery:'Jewellery',belt:'Belts',hat:'Hats',eyewear:'Eyewear',scarf:'Scarves',hosiery:'Socks & tights',accessory:'Other accessories'};
export const accessoryCategories=['bag','jewellery','belt','hat','eyewear','scarf','hosiery','accessory'];
export const colours={White:'#eeeae0',Black:'#30312f',Beige:'#c9baa0',Indigo:'#3a4b59',Denim:'#728692',Tan:'#b69a75',Navy:'#37424d',Charcoal:'#545650',Olive:'#747b5b',Cream:'#ded7c3',Brown:'#82664d',Sage:'#a0aa8b',Rust:'#b17659',Grey:'#999992',Pink:'#d7a9b7',Red:'#b74949',Blue:'#618bac',Green:'#779a71',Yellow:'#d7bd63',Purple:'#94799f',Multicolour:'#b6a1a5'};
// Retailer-scoped searches, not claims of current stock or exact product matches.
export const retailers=[{name:'Woolworths',domain:'woolworths.co.za'},{name:'Mr Price',domain:'mrp.com'},{name:'Superbalist',domain:'superbalist.com'},{name:'Bash',domain:'bash.com'},{name:'Foschini',domain:'bash.com/foschini'},{name:'Truworths',domain:'truworths.co.za'},{name:'Poetry',domain:'poetrystores.co.za'},{name:'Pick n Pay Clothing',domain:'pnpclothing.co.za'}];
export const retailerLink=s=>'https://www.google.com/search?q='+encodeURIComponent('site:'+(retailers.find(r=>r.name===s.retailer)||retailers[3]).domain+' '+s.name);
export const blankState=()=>({version:2,items:[],outfits:[],moods:[],plans:{},trips:[],wishlist:[],wearLog:[],profile:{name:'',gender:'',fit:'Relaxed',styles:['Minimal'],top:'',bottom:'',shoe:'',city:'Johannesburg'}});
const text=(v,n=300)=>typeof v==='string'?v.slice(0,n):'';
const img=v=>typeof v==='string'&&v.length<12_000_000&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v)?v:'';
export function pinterestUrl(s){if(!s)return '';try{const u=new URL(s);if(u.protocol!=='https:')return '';const h=u.hostname.toLowerCase();return h==='pin.it'||h==='pinterest.com'||h.endsWith('.pinterest.com')?u.href:'';}catch{return '';}}
export function validateState(raw){
 if(!raw||!Array.isArray(raw.items)||raw.items.length>500)throw Object.assign(Error('This is not a supported wardrobe backup.'),{status:400});const clean=blankState(),ids=new Set();
 clean.tutorialComplete=raw.tutorialComplete===true;
 clean.stylistFeedback=(raw.stylistFeedback||[]).slice(-40).filter(x=>x&&typeof x.reason==='string').map(x=>({reason:text(x.reason,100),note:text(x.note,300),context:text(x.context,1200),outfit:text(x.outfit,100),created:Number(x.created)||Date.now()}));
 clean.profile={...clean.profile,...Object.fromEntries(Object.keys(clean.profile).filter(k=>k!=='styles').map(k=>[k,text(raw.profile?.[k],80)])),styles:Array.isArray(raw.profile?.styles)?raw.profile.styles.map(s=>text(s,40)).slice(0,12):[]};
 if(!['Female','Male','Unspecified',''].includes(clean.profile.gender))clean.profile.gender='Unspecified';
 const personal=raw.personal||{};
 clean.personal={completed:personal.completed===true,photo:img(personal.photo),usePhoto:personal.usePhoto===true&&!!img(personal.photo),bodyShape:text(personal.bodyShape,120),bodyNotes:text(personal.bodyNotes,500),lifestyle:text(personal.lifestyle,200),favouriteColours:text(personal.favouriteColours,200),avoid:text(personal.avoid,300),goals:text(personal.goals,300),comfort:text(personal.comfort,200),budget:text(personal.budget,30)};
 clean.items=raw.items.filter(i=>i&&!/^w(?:[1-9]|1[0-4])$/.test(i.id)).map(i=>{if(!i.id||ids.has(i.id)||!categories[i.cat])throw Object.assign(Error('One wardrobe item is invalid.'),{status:400});ids.add(i.id);return {id:text(i.id,100),name:text(i.name,80)||'Untitled piece',cat:i.cat,colour:colours[i.colour]?i.colour:'Multicolour',style:text(i.style,40),material:text(i.material,80),brand:text(i.brand,80),size:text(i.size,30),fit:text(i.fit,40),formality:[1,2,3].includes(Number(i.formality))?Number(i.formality):1,price:Math.max(0,Number(i.price)||0),worn:Math.max(0,Math.floor(Number(i.worn)||0)),fav:!!i.fav,laundry:!!i.laundry,created:Number(i.created)||Date.now(),image:img(i.image)};});
 clean.outfits=(Array.isArray(raw.outfits)?raw.outfits:[]).slice(0,80).filter(o=>o&&Array.isArray(o.ids)&&o.ids.every(id=>ids.has(id))).map(o=>({id:text(o.id,100),batch:text(o.batch,100),name:text(o.name,100),ids:o.ids.slice(0,12),suggestions:(o.suggestions||[]).slice(0,12).map(s=>({name:text(s.name,100),category:categories[s.category]?s.category:'accessory',retailer:retailers.some(r=>r.name===s.retailer)?s.retailer:'Bash'})),reason:text(o.reason,1200),occasion:text(o.occasion,300),weather:text(o.weather,60),gender:text(o.gender,30),created:Number(o.created)||Date.now(),saved:!!o.saved,image:img(o.image),renderStatus:['pending','ready','failed'].includes(o.renderStatus)?o.renderStatus:'pending',renderError:text(o.renderError,500),source:o.source==='Imported'?'Imported':'AI'}));
 if(raw.version===1&&Array.isArray(raw.saved))for(const o of raw.saved){if(!Array.isArray(o.ids)||!o.ids.every(id=>ids.has(id)))continue;clean.outfits.push({id:text(o.id,100),batch:'imported',name:text(o.name,100),ids:o.ids,suggestions:(o.suggestions||[]).map(s=>({name:text(typeof s==='string'?s:s.name,100),retailer:'Bash',category:'accessory'})),reason:'Imported from your previous Closet.',gender:'',occasion:text(o.occasion),saved:true,image:'',renderStatus:'pending',source:'Imported',created:Date.now()});}
 for(const o of clean.outfits){const original=(raw.outfits||[]).find(x=>x.id===o.id);o.tryOnImage=img(original?.tryOnImage);o.tryOnError=text(original?.tryOnError,500);o.tryOnStatus=['ready','failed'].includes(original?.tryOnStatus)?original.tryOnStatus:'pending';if(original?.source==='Styled by you')o.source='Styled by you';}
 clean.moods=(raw.moods||[]).slice(0,100).map(m=>({id:text(m.id,100),name:text(m.name,80),note:text(m.note,800),url:pinterestUrl(m.url),image:img(m.image)}));
 const looks=new Set(clean.outfits.map(o=>o.id));for(const [date,plan]of Object.entries(raw.plans||{})){const id=typeof plan==='string'?plan:plan?.id;if(/^\d{4}-\d{2}-\d{2}$/.test(date)&&looks.has(id))clean.plans[date]=id;}
 clean.trips=(raw.trips||[]).slice(0,100).map(t=>({id:text(t.id,100),name:text(t.name,100),start:text(t.start,10),end:text(t.end,10),ids:(t.ids||[]).filter(id=>ids.has(id)),checked:(t.checked||[]).filter(id=>ids.has(id))}));
 clean.wishlist=(raw.wishlist||[]).slice(0,100).map(w=>({id:text(w.id,100),name:text(w.name,100),brand:text(w.brand,60),note:text(w.note,500),price:Math.max(0,Number(w.price)||0),url:/^https:\/\//.test(w.url||'')?text(w.url,2000):''}));
 clean.wearLog=(raw.wearLog||[]).slice(-3000).map(l=>({date:text(l.date,10),ids:(l.ids||[]).filter(id=>ids.has(id))}));return clean;
}
export const outfitSignature=o=>JSON.stringify([...(o.ids||[])].sort())+'|'+JSON.stringify((o.suggestions||[]).map(s=>s.name.trim().toLowerCase()).sort());
export function validateOutfits(outfits,items,anchor){if(!Array.isArray(outfits)||outfits.length!==3)throw Error('Expected three outfits');const ids=new Set(items.map(i=>i.id));for(const [index,o]of outfits.entries()){if(!Array.isArray(o.ids)||o.ids.some(id=>!ids.has(id))||new Set(o.ids).size!==o.ids.length)throw Error('Unknown item');if(index<2&&(!o.ids.length||(anchor&&!o.ids.includes(anchor))))throw Error('Missing owned piece');if(!o.name||!Array.isArray(o.suggestions)||o.suggestions.some(s=>!s.name||!retailers.some(r=>r.name===s.retailer)))throw Error('Invalid outfit');}if(new Set(outfits.map(outfitSignature)).size!==3)throw Error('Duplicate outfits');return outfits;}
