import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createSocial} from '../social-ui.js';
import {createStudio} from '../outfit-studio.js';
import {createNotifications} from '../notifications-ui.js';

function environment(){const handlers={},dialog={classList:{add(){}},close(){}};const previous=globalThis.document;globalThis.document={addEventListener(type,fn){(handlers[type]??=[]).push(fn);},querySelector(){return dialog;}};return {async click(dataset){const b={dataset,isConnected:true};for(const fn of handlers.click||[])await fn({target:{closest(){return b;}}});},input(form,value){for(const fn of handlers.input||[])fn({target:{value,closest(){return form;}}});},async submit(form){for(const fn of handlers.submit||[])await fn({target:form,preventDefault(){}});},restore(){globalThis.document=previous;}};}
test('notifications filter unread items and return from an announcement to the same filter',async()=>{const env=environment(),originalInterval=globalThis.setInterval;globalThis.setInterval=()=>0;let html='';const items=[{id:'a',kind:'announcement',title:'Welcome',body:'Hello',read:false},{id:'b',kind:'friend',title:'Friend outfit',body:'A look',read:true}];try{const center=createNotifications({getUser:()=>({id:'u'}),api:async()=>({items}),modal(t,b){html=b;},toast(){}});await center.open();assert.match(html,/Friend outfit/);await env.click({notice:'filter',id:'unread'});assert.doesNotMatch(html,/Friend outfit/);assert.match(html,/Welcome/);await env.click({notice:'open',id:'a'});assert.match(html,/Back to notifications/);await env.click({notice:'back'});assert.match(html,/all caught up/);assert.doesNotMatch(html,/Friend outfit/);}finally{env.restore();globalThis.setInterval=originalInterval;}});
test('feed comments expand inline and keep a draft across likes and feed refreshes',async()=>{const env=environment();let modals=0;const post={id:'p',name:'Sunday',author:{id:'a',name:'Alice',username:'alice'},pieces:[],comments:[{id:'c',text:'<hello>',author:{id:'a',name:'Alice'}}]};try{const social=createSocial({getState:()=>({items:[]}),getUser:()=>({id:'b'}),isGuest:()=>false,api:async()=>({posts:[post]}),modal(){modals++;},refresh(){},toast(){}});await social.load();await env.click({social:'comments',id:'p'});assert.equal(modals,0);assert.match(social.page(),/aria-expanded="true"/);assert.match(social.page(),/feed-comment-form/);assert.match(social.page(),/&lt;hello&gt;/);env.input({dataset:{id:'p'}},'My unfinished comment');await env.click({social:'like',id:'p'});assert.match(social.page(),/My unfinished comment/);social.clear();assert.doesNotMatch(social.page(),/My unfinished comment/);}finally{env.restore();}});
test('swap Back preserves selected piece and view; save opens new pieces without altering original',async()=>{const env=environment(),oldFormData=globalThis.FormData;let html='',title='';const state={items:[{id:'t1',cat:'top',name:'Original top'},{id:'t2',cat:'top',name:'New top'},{id:'b',cat:'bottom',name:'Skirt'}],outfits:[{id:'o',name:'Look',ids:['t1','b'],suggestions:[],tryOnImage:'photo',saved:true}],profile:{}};try{const studio=createStudio({getState:()=>state,commit:async fn=>{fn(state);return true;},modal(t,b){title=t;html=b;},isBusy:()=>false,toast(){},refresh(){}});studio.open('o');await env.click({studio:'piece',key:'1'});await env.click({studio:'swap',key:'1'});assert.match(html,/Back to outfit/);await env.click({studio:'back',key:'o'});assert.match(html,/class="btn primary" data-studio="view" data-key="me"/);assert.match(html,/piece-tile selected[^]*data-key="1"/);await env.click({studio:'swap',key:'0'});globalThis.FormData=class{get(key){return key==='replacement'?'t2':null;}};await env.submit({id:'swap-piece',dataset:{id:'o',index:'0'},querySelector(){return {};}});assert.deepEqual(state.outfits[0].ids,['t2','b']);assert.deepEqual(state.outfits[1].ids,['t1','b']);assert.match(html,/class="btn primary" data-studio="view" data-key="look"/);assert.match(title,/my edit/);}finally{env.restore();globalThis.FormData=oldFormData;}});
